# Generated by Django 5.0.4 on 2024-06-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_cliente_cnpj_alter_cliente_cpf_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultaDTE",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criando em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("aguardando_leitura", models.SmallIntegerField(default=0)),
                ("aceite_pessoalmente", models.SmallIntegerField(default=0)),
                ("recusada_pessoalmente", models.SmallIntegerField(default=0)),
                ("cancelada", models.SmallIntegerField(default=0)),
                ("lida", models.SmallIntegerField(default=0)),
                ("aceite_via_dte", models.SmallIntegerField(default=0)),
                ("recusada_via_dte", models.SmallIntegerField(default=0)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.cliente")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
