# Generated by Django 5.0.4 on 2024-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskPartialResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criando em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("task_id", models.UUIDField()),
                (
                    "clientes_finalizados",
                    models.JSONField(default=list, verbose_name="Cliente com execução finalizada"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="consultadte",
            options={"verbose_name": "Consulta DTE", "verbose_name_plural": "Consultas DTE"},
        ),
    ]
