# Generated by Django 5.0.4 on 2024-06-12 00:03

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[core.validators.valida_tamanho_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[core.validators.valida_tamanho_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="razao_social",
            field=models.CharField(max_length=255, verbose_name="Razão Social"),
        ),
    ]
